### ISSUE TITLE
The logrotate package should be 'present' by default, or at least tunable

### ISSUE THREAD

**Issue by natemccurdy** [yo61/puppet-logrotate#11]
This issue is the same issue from rodjek's original project, rodjek/puppet-logrotate#58. I'm just pulling it into yo61's fork because I agree with the original issue.

There is a PR that proposed a fix at rodjek/puppet-logrotate#59

---

Currently the package's state is not a class parameter in logrotate::base and its default value of 'latest' doesn't seem to be justified.

If ever YUM is used by another user/process at the same time as a Puppet run or if the repositories are too slow to answer, that shows up as a failure in the run.

**Comment by robinbowes** [comment]
I think I've refactored since that issue/PR was created. There is no longer a logroate::base class, and the logrotate class has an "ensure" parameter.

Can you check that meets your requirements?

R.

**Comment by natemccurdy** [comment]
Hi @robinbowes . Ah, you're right, there is an ensure parameter. Sorry, I must've just assumed there wasn't one when I saw that the package was trying to be upgraded.

However, I am of the mindset that it is best to default packages to "installed" or "present". That way the end-user can choose when to upgrade if needed.

**Comment by robinbowes** [comment]
I wouldn't disagree with that. PR welcome ;)
