### ISSUE TITLE
wtmp and btmp are different when using the future parser

### ISSUE THREAD

**Issue by natemccurdy** [yo61/puppet-logrotate#13]
I noticed that when using Puppet 4 and/or the future parser, the default wtmp and btmp rules are being made with different options set. Specifically, they are missing: `compress`, `delaycompress`, and `notifempty`.

This is happening on RedHat nodes with a stock Puppet Enterprise 3.8.2 installation.

Puppet version: 3.8.2
Ruby version: ruby 1.9.3p551

Here's a puppet 3 parser vs. future parser diff of the resource:

```diff
file[/etc/logrotate.d/wtmp]  
    file{"/etc/logrotate.d/wtmp":  
         backup => "main"  
         content => {  
-                    checksum =>             "72a136dc57f58796ff8e23686f1bcd02",  
+                    checksum =>             "6e830130e1660b31f445d32314e51578",  
                     content =>             "# THIS FILE IS AUTOMATICALLY DISTRIBUTED BY PUPPET. ANY CHANGES WILL BE  
 # OVERWRITTEN.  
   
 /var/log/wtmp {  
-  compress  
   create 0664 root utmp  
-  delaycompress  
   minsize 1M  
   monthly  
   nomissingok  
-  notifempty  
   rotate 1  
 }  
 ",
``` 

```diff
file[/etc/logrotate.d/btmp]  
    file{"/etc/logrotate.d/btmp":  
         backup => "main"  
         content => {  
-                    checksum =>             "2b48a089a480d0a58255ee662b2f066a",  
+                    checksum =>             "8d8fad6501d5a201dbafc5eea144bea1",  
                     content =>             "# THIS FILE IS AUTOMATICALLY DISTRIBUTED BY PUPPET. ANY CHANGES WILL BE  
 # OVERWRITTEN.  
   
 /var/log/btmp {  
-  compress  
   create 0600 root utmp  
-  delaycompress  
   minsize 1M  
   missingok  
   monthly  
-  notifempty  
   rotate 1  
 }  
 ",
```

**Comment by robinbowes** [comment]
Can you share the code you're using to test this?

**Comment by robinbowes** [comment]
I've double-checked the test coverage (spec/classes/defaults_spec.rb) and I can't reproduce this.

See the travis test output here: https://travis-ci.org/yo61/puppet-logrotate/builds/97110228

Please re-open if you can give me code that reproduces the issue.

**Comment by natemccurdy** [comment]
@robinbowes Thanks for adding the tests, and sorry for the delay in response. I don't have access to the code that was causing the issue I was seeing, but I'm leaning towards the problem being due to leaking resource defaults in different parts of the code base (my code base).

If I am able to track down some code, I'll re-open and add to this ticket.

**Comment by acidprime** [comment]
I am having the same issue here, can we re-open? My circumstances is Puppet 4 (ruby 2) compiling a catalog for Puppet 3 with ruby 1.8.7.

**Comment by natemccurdy** [comment]
@robinbowes I was able to reliably replicate the issue with Puppet version 3.6.2 and 3.8.x:
```puppet
logrotate::rule { "thing":
  path          => '/var/log/fake.log',
  compress      => true,
  delaycompress => true,
  dateext       => true,
}
```
```shell
root@foss-master:~# puppet --version
3.6.2
root@foss-master:~# ruby --version
ruby 1.8.7 (2012-02-08 patchlevel 358) [x86_64-linux]
```

What's going on is that the `compress`, `delaycompress`, and `dateext` parameters of a `logrotate::rule` declaration are leaking into the `wtmp` and `btmp` rules defined in `logrotate::defaults`.

When I comment out any one of those parameters in the Puppet code above and re-run puppet apply against it, `wtmp` and `btmp` also change to reflect the commented out parameter.

**Likely Cause**
The `scope` lookup happening in the ERB template that builds these files is looking at the wrong scope in older versions of Puppet. There were always issues with dynamic scoping in older Puppet versions, and the issue in this ticket is a side-effect of that.

**Comment by acidprime** [comment]
You likely are not catching this in your specs as you don't do a host manifest with defining a rule and then including your class.
