### ISSUE TITLE
string 'undef' now treated as undef

### ISSUE THREAD

**Issue by durist** [yo61/puppet-logrotate#26]
This module recently stopped working for me due to the string "undef" being treated as value undef; some discussion here:
https://groups.google.com/forum/#!topic/puppet-users/X-XrjM9oJYE

This is probably a bug in puppet; nevertheless maybe there is a safer way for the module to handle undefined values?

**Comment by robinbowes** [comment]
With which version of puppet are you seeing problems? It's tested on version 3.5.0 - 4.3.0 with strict variables enabled.

**Comment by mwasilew2** [comment]
I'm seeing the same with Logrotate::Conf[/etc/logrotate.conf] . undef is not recognized so it fails with an error message.

This is on CentOS 1511, pc1 repo, puppet-agent 1.5.0-1.el7, puppetserver 2.4.0-1.el7

Downgrading server to 2.3.2-1.el7 made the problem go away.

This looks like the source of the change: https://tickets.puppetlabs.com/browse/PUP-6176

**Comment by robinbowes** [comment]
What version of puppet is that?

**Comment by mwasilew2** [comment]
sorry, had to downgrade puppet agent as well to fix it

it works with 4.4.2 (agent 1.4.2 and server 2.3.2)
it breaks with 4.5 (agent 1.5.0 and server 2.4.0)

**Comment by robinbowes** [comment]
That's unfortunate - why are there breaking semantics in a non-major version release?

**Comment by durist** [comment]
I filed a bug: https://tickets.puppetlabs.com/browse/SERVER-1356

**Comment by hlindberg** [comment]
The bug that caused this will be released in puppet 4.5.1

**Comment by durist** [comment]
I've created a pull request for a fix that just changes the string "undef" to "UNDEFINED".

**Comment by robinbowes** [comment]
Fixed in 1.4.0
