### ISSUE TITLE
Ubuntu Xenial 16.04 compaibility

### ISSUE THREAD

**Issue by TravellingGuy** [yo61/puppet-logrotate#34]
The module doesn't work properly with Ubuntu Xenial 16.04, but there's an easy fix.

In defaults.pp, line 10, add 'xenial' to the case statement. Change from this:
`'trusty': {`
to:
`trusty', 'xenial': {`

Sorry, no pull request, as I just manually patched it directly on my server for now. :smile:

**Comment by robinbowes** [comment]
PRs, with passing tests, gratefully received! :)

**Comment by janvonde** [comment]
@robinbowes I don't think that I can fix the failing of the tests on my pull request, or do I?

**Comment by robinbowes** [comment]
It seems that something has changed since the last commit on master and all the tests now fail. I am investigating. I suspect your change will work just fine once the tests are fixed. I'll merge once that's sorted.

R.

**Comment by edestecd** [comment]
I suggest not using lsbdistcodename and instead checking that the OS version is greater than 14.04, so we don't have to keep fixing this on subsequent releases.  We can just assume it is the same until we discover otherwise....  I'm digging up some code from the apt module now...

**Comment by edestecd** [comment]
THis is much more robust (imho):
https://github.com/puppetlabs/puppetlabs-apt/commit/e651d7d25c43577738f060d1a2d31a58e273934b
https://github.com/puppetlabs/puppetlabs-apt/blob/master/manifests/params.pp#L125
