### ISSUE TITLE
Dependency issue in manifests/rule.pp

### ISSUE THREAD

**Issue by robinbowes** [yo61/puppet-logrotate#7]
Marcello raised this PR:

https://github.com/rodjek/puppet-logrotate/pull/57

He is seeing a problem when overriding module parameters in Foreman

@tchellomello - can you give me some details of how you are using this when you see the issue?

**Comment by tchellomello** [comment]
Hello, 

  Basically we can experience this issue when the module is used on Foreman.

 After uploading this module and trying to use it on Foreman, when running puppet agent we get this error.  

  After removing it, we were able to successfully override any value using the Foreman webUI and deploy the module as expected. 

   Please let me know if you need any information.

**Comment by moritzfriedrich** [comment]
We have the same issue.
Error: Could not apply complete catalog: Found 1 dependency cycle:
(File[/etc/logrotate.d/acpid] => Logrotate::Rule[acpid] => Class[Logrotate] => File[/etc/logrotate.d/acpid])

The rules are included by hiera, so we only call the Logrotate class (init.pp).

From my point of view, the require class option is only usefull if use logrotate::rule detached.

**Comment by robinbowes** [comment]
So, as far as I can see, the `require => Class['logrotate']` is used to ensure that logrotate is installed and the /etc/logrotate.d directory exists before writing the rule.

You are using logrotate class with rules specified as params to the main class. This causes the problem because the logrotate::rule class is called from the main class.

Ok, I think I understand now.

I will break out the package install into a separate class and add a dependency on that which should both satisfy the original requirement and fix this issue.

**Comment by robinbowes** [comment]
Can you check the develop branch at 0af1d09abc21367c66487538bafa295371b784b6 and confirm how that works for you please? If it's good, I'll cut a new release.

**Comment by moritzfriedrich** [comment]
For me this fix is working fine. Thank you.

**Comment by robinbowes** [comment]
Released in v1.2.8
